---
apiVersion: v1
kind: Service
metadata:
  name: platform-service
  labels:
    app: platform
spec:
  type: NodePort
  selector:
    app: platform
  ports:
  - name: platform-port
    port: 80
    targetPort: 80
